### ISSUE TITLE
Project Check list

### ISSUE THREAD

**Issue by DominikKarski** [Isseii/TPR_Automatic_Library#1]
# Task 1 Check list

- [x] text is in C# and use .NET
- [x] build succeeded
- [x] all UT are green
- [x] Object model representing process data
  - [x] structured data is used to create object model
  - [x] Users: a collection of all actors relevant to the implemented business process (e.g.: readers, customers, suppliers, etc)
  - [x] Catalog: a dictionary of the goods descriptions (e.g.: books, good )
  - [x] Process state: description of the current process state (e.g: the current content of the shop, library, etc.)
  - [x] Events: description of **all** events contributing to the process state change in time (polymorphic approach)
- [x] Dependency injection (additional framework is not required)
- [x] `Data` layer is clearly stated using language terms only (no database of file access is required)
- [x] `Data` API is abstract
- [x] `Logic` layer is clearly stated using language terms only
- [x] `Logic` API is clearly stated
- [x] `Logic` uses only the abstract `Data` layer API
- [x] Unit Test - 2+ testing data generation methods
- [x] layers are tested independently
- [x] only code in the solution is tested
